version: "3.8"
services:
  db:
    build: ./database/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5432"]
      interval: 30s
      timeout: 10s
      retries: 5
  etl:
    build: ./
    depends_on:
      - db
    restart: on-failure
    links: 
      - db